
models:
  - name: dim_listings_cleansed
    description: Cleansed table containing listings
    data_tests:
     - min_row_c:
        arguments:
          min_rows: 1000
       # severity: warn
    columns:
       - name: listing_id
         description: primary key for listing
         data_tests: #historically just tests:
          - unique
          - not_null

       - name: host_id
         description: key to join hosts table
         data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleansed')
                field: host_id

       - name: room_type
         description: type of room
         data_tests:
          - accepted_values:
              arguments:
                values: ['Entire home/apt','Private room','Shared room','Hotel room']

       - name: minimum_nights
         description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
         data_tests: 
          - pos_val

  - name: dim_hosts_cleansed
    config:
      contract:
        enforced: true
    columns:
       - name: host_id
         description: primary key for hosts
         data_type: integer
       - name: host_name
         description: name of the host
         data_type: string
       - name: is_superhost
         description: flag for being supehost, whatever is the business meaning of this - ask the primary business stakeholder, TO DO insert his email there via separate .md file
         data_type: string
       - name: updated_at
         description: timestamp when the host entry was updated last timee
         data_type: timestamp
       - name: created_at
         description: timestamp when the host entry was inserted into the database
         data_type: timestamp

  - name: dim_listings_with_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
          #group_by: [col1, col2] # (Optional)
          #compare_group_by: [col1, col2] # (Optional)
          #factor: 1 # (Optional)
          #row_condition: "id is not null" # (Optional)
          #compare_row_condition: "id is not null" # (Optional)
    columns:
       - name: price
         tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50 # (Optional)
              max_value: 500 # (Optional)
            #group_by: [group_id, other_group_id, ...] # (Optional)
            #row_condition: "id is not null" # (Optional)
            #strictly: false # (Optional. Default is 'false'. Adds an 'or equal to' to the comparison operator for min/max)
          - dbt_expectations.expect_column_max_to_be_between:
              arguments:
                max_value: 10000
              config:
                severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: number





